import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";

export default function Header(props) {
	return (
		<>
			<Head>
				<title>Fabrizhio A. ~ {props.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className={styles.header}>
				<div></div>
				<div className={styles.navigationBar}>
					<Link href="/">
						<a className={styles.navigationLink}>Inicio</a>
					</Link>
					<Link href="/about">
						<a className={styles.navigationLink}>Sobre mi</a>
					</Link>
					<Link href="/galery/">
						<a className={styles.navigationLink}>Galeria</a>
					</Link>

					<Link href="/contact">
						<a className={styles.navigationLink}>Contactame</a>
					</Link>
				</div>
			</header>
		</>
	);
}
